### ISSUE TITLE
Mouslook causing cycles viewport to blank out on pen drag/rotate/zoom

### ISSUE THREAD

**Issue by CoreyCorza** [dairin0d/mouselook-navigation#3]
Soo with the latest version of mouselook and 3.0, if Im in cycles/render viewport and I use my pen to rotate/pan/zoom, cycles will go blank for a split second before starting the sample count again.
Just a little bit annoying having to turn off mouselook, put my pen down then find my mouse - when I need to quickly preview something in render viewport - and then pick back up my pen and turn mouselook back on to resume using my tablet.
Otherwise, everything else seems to be working good lately. Loving the occasional updates and tweaks.
Thanks mate.

**Comment by CoreyCorza** [comment]
![MEvVfEZhYy](https://user-images.githubusercontent.com/40785775/137583475-525f225c-7b3f-4786-813b-0edde3d16b2a.gif)

**Comment by dairin0d** [comment]
Thanks! Unfortunately, I don't know how to reproduce this issue.
I downloaded a fresh 3.0.0 alpha build, opened the default scene, switched the render engine to cycles, and tried rotating the view (both via the built-in navigation and using the addon). No difference, as far as I can tell... Does the problem appear for you in the default scene too? Or, perhaps, you can upload your scene somewhere so I could try it myself?

**Comment by CoreyCorza** [comment]
![RiuzRqNkVt](https://user-images.githubusercontent.com/40785775/138454194-64a511e2-aa5d-4b93-b33f-b53aa9dbb0b3.gif)
I reinstalled the latest 3.0 and reinstalled mouselook, completely removing all other previous installation data and still does the same thing on a default scene.
I am noticing when the glitch occurs, in the top left hand corner in statistics its show a message "loading something to do with BVH - loading kernal may take some time" which isn't present when mouselook is turned off.
Haven't changed anything from defaults other than loaded the zbrush profile for mouselook

**Comment by CoreyCorza** [comment]
![B1BSeBovoi](https://user-images.githubusercontent.com/40785775/138457394-5254ba93-1138-47dd-8e12-58313d88990b.gif)
Further investigation: Zbuffer appears to be the cause of the issue

**Comment by dairin0d** [comment]
I see now :-) I didn't initially notice that you were using ZBrush mode, sorry. Now I am able to reproduce the problem (and it's not exclusive to Blender 3.0, apparently).

Unfortunately, there doesn't seem to be anything I can do about it (triggering a redraw is the only way to get the viewport's depth buffer from a script). If it's any consolation, I made an explicit mention about this in the [addon's documentation](https://github.com/dairin0d/blender-2.8-scripts/blob/master/docs/mouselook_navigation/mouselook_navigation.md).

**Comment by CoreyCorza** [comment]
Ahh bummer! Thats alright setting it to raycast or selection is fine. 
One more question/issue: With rotating around last brush stroke not being supported in blender, I found a work around for pivoting around the 3d cursor - n panel>viewlock> Lock - to 3d cursor. And it works great in general until I turn on mouselook, it will rotate around the 3d cursor but no panning, for some reason? Panning seems to be disabled using alt+click (zbrush profile) with "Lock - to 3d cursor" activated. Is this a known issue or would you mind taking at look at that at some point? 
If I could both rotate and pan around the 3dcursor while Im working on large objects/zoomed into details this would be soooo good, finding a workable pivot method in blender is so friggen annoying and this would be amazing. Almost as good as zbrush's rotate around last brush stoke method, at least I could choose where Im pivoting

**Comment by CoreyCorza** [comment]
![iZbKxbEllN](https://user-images.githubusercontent.com/40785775/138493958-4bd6fcd1-4217-467a-8b85-92c5b691f7b1.gif)

**Comment by CoreyCorza** [comment]
It is supported with blenders native panning but not mouselooks zbrush profile alt+click panning

**Comment by dairin0d** [comment]
Another bummer. There doesn't seem to be any way for scripts to change the view's offset when in the "locked to 3D cursor mode" (Blender simply ignores any modifications to the view matrix in this mode, and does not expose any other APIs to affect the underlying state).

They only workaround I can think of would be to change the position of the 3D cursor itself, but that's probably not what you want.

**Comment by CoreyCorza** [comment]
https://user-images.githubusercontent.com/40785775/138518554-57d66f5b-67d3-449b-ab8b-8f385dbf062e.mp4

Dang that sucks!
Yeah even changing the 3d mouse coordinates from the n-panel, the 3d cursor would still have to be panned into the middle of the view to be effective. And if say, Im working on the legs, Id still need to pan up to the head to put the cursor there in the centre of view. Apparently there is no option too for recentering view when in locked to 3d cursor mode *sigh*.
All good, I'll find a workaround with blenders native middle click panning as that does work. 

Thanks for keeping this addon maintained and updated too btw, and being so responsive on issues. Heaps appreciated. Love your work
